name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: "us-east-2"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      
      # ZIP the lambda function
      - name: ZIP the lambda function
        run: zip -r lambda_function.zip lambda_function.py

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Terraform: Initialize and Apply
      - name: Terraform Init and Apply
        working-directory: .
        run: |
          terraform init
          terraform import aws_iam_role.lambda_exec arn:aws:iam::050451358673:role/lambda_exec_role
          terraform apply -auto-approve
